name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Check syntax with ruff
      run: uv run ruff check . --select=E9,F63,F7,F82

    - name: Check code formatting with black
      run: uv run black --check .

    - name: Check imports with isort
      run: uv run isort --check-only .

    - name: Lint with flake8
      run: uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics